### ISSUE TITLE
apt update not fetching from neonvm

### ISSUE THREAD

**Issue by kubeworkz** [neondatabase/autoscaling#105]
## Steps to reproduce
`kubectl exec -it $(kubectl get neonvm vm-debian -ojsonpath='{.status.podName}') -- screen /dev/pts/0`
`apt-get update >/dev/null && apt-get install -y curl >/dev/null`

## Expected result
App update and install curl

## Actual result
```
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Connection timed out [IP: 151.101.210.132 80]
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Connection timed out [IP: 146.75.30.132 80]
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Connection timed out [IP: 199.232.162.132 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Environment
K3s cluster at Hetzner (server version: `v1.26.0+k3s1`)

**Comment by vadim2404** [comment]
@cicdteam to validate.

**Comment by cicdteam** [comment]
Not reproducible

1. setup local k3d cluster and deploy autoscaling
```console
make k3d-setup
make docker-build
make deploy
```

2. VM spec
```yaml
apiVersion: vm.neon.tech/v1
kind: VirtualMachine
metadata:
  name: vm-debian
spec:
  guest:
    cpus:
      min: 1
    memorySlotSize: 1Gi
    memorySlots:
      min: 1
    rootDisk:
      image: neondatabase/vm-debian:11
```

2. create VM and check apt-get
```console
kubectl apply -f vm.yaml
kubectl exec -it $(kubectl get neonvm vm-debian -ojsonpath='{.status.podName}') -- screen /dev/pts/0

root@neonvm:~# curl --version
-bash: curl: command not found
root@neonvm:~# apt-get update >/dev/null && apt-get install -y curl >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@neonvm:~# curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1w zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
root@neonvm:~# 
```
