### ISSUE TITLE
Scheduler has a memory leak (again)

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#409]
Introduced by v0.13.0, AFAICT. Probably #399. The graph looks like this:

![Graph of scheduler memory usage over two days, starting at 07/13, staying steady at about 100 MB. On 07/14, it drops briefly, then starts rising quickly to nearly 500 MB by the end of the day.](https://github.com/neondatabase/autoscaling/assets/29154784/98a293df-a743-4696-b375-1dd72eabcd98)

I'll edit this comment as I progress.

---

**Initial guess:**

In the previous memory leak issue (#248), the cause ended up being that nodes weren't getting cleaned up. Reading the scheduler's state from the "dump state" endpoint shows there's nothing out of the ordinary; all expected pods and nodes are represented, and no extras.

**What about pprof?**

The scheduler exposes the pprof HTTP endpoint on port 7777. The heap profile looks like this:

<details>
<summary>Image of heap profile (long)</summary>

![Graph of allocations. The biggest groups of allocations are from various K8s pod components, originating at (*AutoscaleEnforcer).watchPodEvents](https://github.com/neondatabase/autoscaling/assets/29154784/7a250fa6-3b59-409a-87e0-92dc8b2c8236)

</details>

So, broadly, we have a bunch of K8s `corev1.Pod` objects sitting around, not getting deallocated. And they originally came from `watchPodEvents`, which makes sense — outside of the core scheduler, that's the main place that we get `Pod` objects.

The _main_ thing that changed between v0.12.0 and v0.13.0 there is that we have new handlers, which pass the _whole_ `*corev1.Pod` object, instead of something derived from it.

**Reproducing locally**

Well, it reproduces locally. With a local kind cluster, I ran this script a bunch of times in parallel:

<details>
<summary> pod-loop.sh </summary>

```sh
#!/usr/bin/env bash

set -eu -o pipefail

if [ "$#" -lt 1 ] || [ -z "$1" ]; then
    echo "Missing name"
    exit 1
fi

name="$1"

# 10k is just a big number; we won't get nearly that many.
for c in $(seq 1 10000); do
    cat pod-deploy.yaml | yq --arg name "$name" '.metadata.name |= $name' | kubectl apply -f -
    while true; do
        sleep 1s
        json="$(kubectl get pod "$name" -o json 2>/dev/null || continue)"

        if [ "$(echo "$json" | jq -r '.status.phase')" = "Running" ]; then
            break
        fi
    done

    echo "$c" > "debug-counts/$name"

    sleep 3s
    kubectl delete pod --grace-period 0 "$name"

    while true; do
        sleep 1s
        kubectl get pod "$name" 2>/dev/null || break
    done

    sleep 3s
done
```

</details>

<details>
<summary> pod-deploy.yaml </summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    test: foo
spec:
  schedulerName: autoscale-scheduler
  containers:
    - name: alpine
      image: alpine:3.16
      args: ["sleep", "30s"]
      resources:
        requests:
          cpu: 10m
          memory: 40Mi
      env:
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_1
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_2
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_3
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_4
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_5
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_6
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_7
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_8
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_9
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_10
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_11
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_12
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_13
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_14
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_15
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_16
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_17
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_18
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_19
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_20
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_21
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_22
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_23
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_24
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_25
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_26
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_27
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_28
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_29
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_30
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_31
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_32
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_33
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_34
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_35
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_36
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_37
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_38
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_39
          value: "Long environment variable! to increase the size of the the containers that we generate"
        - name: TEST_LONG_ENVIRONMENT_VARIABLE_TO_INCREASE_SIZE_40
          value: "Long environment variable! to increase the size of the the containers that we generate"
```

</details>

created with:

```fish
for i in (seq -w 0 99); ./pod-loop.sh test-pod-$i &; sleep 0.1s; end
```

and finished with:

```fish
kill (jobs -p)
kubectl delete pod --grace-period 0 -l test=foo
```

Briefly, running this for 10/20/30 minutes showed memory usage for the schedulers as follows:

| Version | 10m | 20m | 30m | total pods created |
|---|---|---|---|---|
| v0.12.0 | 46 MiB | 49 MiB | 49 MiB | 2743 |
| HEAD | 91 MiB | 143 MiB | 193 MiB | 2783 |

Total pods was calculated with `cat debug-counts/* | jq -s 'add'`. `git describe` at time of testing was `v0.13.0-3-g2713791` (HEAD = 271379148765fec2a3a0a3ed95475862f87cc9fd).

**Final details**

Eventually narrowed down the bug by iteratively running the test above with certain areas of the code commented out. The queue never shrank. Fixed by #415.
