### ISSUE TITLE
Bug: autoscale-scheduler FailedScheduling

### ISSUE THREAD

**Issue by huyongqii** [neondatabase/autoscaling#473]
My environment is:
MacOS: Apple M2 13.2.1 (22D68)
Kubernetes: v1.26.3

I try to deploy neonvm and autoscaler components through the following methods:
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
kubectl apply -f multus.yaml
kubectl apply -f whereabouts.yaml
kubectl apply -f neonvm.yaml
kubectl apply -f autoscale-scheduler.yaml
kubectl apply -f autoscaler-agent.yaml
```
Each of the above pods has been created successfully, and the status is running.
After that I deploy neonvm:
```
apiVersion: vm.neon.tech/v1
kind: VirtualMachine
metadata:
  name: vm-debian
  namespace: kube-system
spec:
  schedulerName: autoscale-scheduler
  guest:
    rootDisk:
      image: neondatabase/vm-ubuntu:22.04
    cpus: { min: 1, use: 1, max: 1 }
    memorySlots: { min: 1, use: 1, max: 5 }
    ports:
      - port: 22   # ssh
      - port: 5432 # postgres
      - port: 9100 # metrics
      - port: 10301 # informant
```
Unfortunately, the status of the pod is always pending, as shown below:
```
Events:
  Type     Reason            Age    From                 Message
  ----     ------            ----   ----                 -------
  Warning  FailedScheduling  14m    autoscale-scheduler  0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling  8m51s  autoscale-scheduler  0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector.
```
I checked the logs of autosacaler-scheduler and found the following problems:
```
{"level":"info","ts":1691985108.6164603,"logger":"autoscale-scheduler.vm-watch","caller":"plugin/watch.go:333","msg":"Skipping update for VM because .status.podName is empty","virtualmachine":{"namespace":"kube-system","name":"vm-debian"}}
{"level":"error","ts":1691985109.7087808,"logger":"autoscale-scheduler.plugin","caller":"plugin/plugin.go:381","msg":"Pod rejected by all Filter method calls","method":"Filter","virtualmachine":{"namespace":"kube-system","name":"vm-debian"},"pod":{"namespace":"kube-system","name":"vm-debian-4q9dk"},"stacktrace":"github.com/neondatabase/autoscaling/pkg/plugin.(*AutoscaleEnforcer).PostFilter\n\t/workspace/pkg/plugin/plugin.go:381\nk8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runPostFilterPlugin\n\t/go/pkg/mod/k8s.io/kubernetes@v1.25.11/pkg/scheduler/framework/runtime/framework.go:776\nk8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).RunPostFilterPlugins\n\t/go/pkg/mod/k8s.io/kubernetes@v1.25.11/pkg/scheduler/framework/runtime/framework.go:759\nk8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne\n\t/go/pkg/mod/k8s.io/kubernetes@v1.25.11/pkg/scheduler/schedule_one.go:110\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.11/pkg/util/wait/wait.go:190\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.11/pkg/util/wait/wait.go:157\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.11/pkg/util/wait/wait.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.11/pkg/util/wait/wait.go:135\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.11/pkg/util/wait/wait.go:190\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.11/pkg/util/wait/wait.go:101"}
```
